#! powershell
param ($silent) 

# check if CrispyCrumbs server already running
# todo insure it's *our* server
$port = 1324
$serverRunning = (Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue) -ne $null

if ($serverRunning) {
    echo "CrispyCrumbs server already running"
    return
}

# Update jwtSecret
if ($silent -ne "y") {
    
    $jwtSecret = Read-Host "Enter new CrispyCrumbs server JWT secret (leave blank to keep previous)"
    $jwtSecret = $jwtSecret -replace '"', '' -replace "'", ''
    
    if ($jwtSecret) {
        echo "//WARNING! this file is generated by init_server.ps1
module.exports = {
  mongodbUri: 'mongodb://localhost:27017/CrispyCrumbs',
  jwtSecret: '$jwtSecret',
};" > .\config\config.js
    }
}
   
# update MongoDB
if (-NOT (Test-Path .\FilesForMongoDB\mongosh.exe)) {
    .\FilesForMongoDB\unzip.exe .\FilesForMongoDB\mongosh.zip -d .\FilesForMongoDB
}

# Clear everything from the CrispyCrumbs database
.\FilesForMongoDB\mongosh.exe CrispyCrumbs --eval "db.dropDatabase()"

# Load data into the CrispyCrumbs database
.\FilesForMongoDB\mongoimport.exe --db CrispyCrumbs --collection users --file .\FilesForMongoDB\CrispyCrumbs.users.json --jsonArray
.\FilesForMongoDB\mongoimport.exe --db CrispyCrumbs --collection videos --file .\FilesForMongoDB\CrispyCrumbs.videos.json --jsonArray

.\FilesForMongoDB\mongosh.exe CrispyCrumbs --eval 'db.videos.createIndex({ title: "text" })'

# Start the server
npm install
node server.js