@echo off
setlocal enabledelayedexpansion

set "port=1324"
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :%port%') do set "pid=%%a"
if defined pid (
    echo CrispyCrumbs server already running
    exit /b
)

set /p jwtSecret="Enter new CrispyCrumbs server JWT secret (leave blank to keep previous): "
if defined jwtSecret (
    set jwtSecret=%jwtSecret:"=%
)
if defined jwtSecret (
    set jwtSecret=%jwtSecret:'=%
)
if defined jwtSecret (
    echo //WARNING. this file is generated by init_server.cmd % > .\config\config.js
    echo module.exports = { >> .\config\config.js
    echo   mongodbUri: 'mongodb://localhost:27017/CrispyCrumbs', >> .\config\config.js
    echo   jwtSecret: '%jwtSecret%', >> .\config\config.js
    echo }; >> .\config\config.js
)

if not exist .\FilesForMongoDB\mongosh.exe (
    .\FilesForMongoDB\unzip.exe .\FilesForMongoDB\mongosh.zip -d .\FilesForMongoDB
)

.\FilesForMongoDB\mongosh.exe CrispyCrumbs --eval "db.dropDatabase()"
.\FilesForMongoDB\mongoimport.exe --db CrispyCrumbs --collection users --file .\FilesForMongoDB\CrispyCrumbs.users.json --jsonArray
.\FilesForMongoDB\mongoimport.exe --db CrispyCrumbs --collection videos --file .\FilesForMongoDB\CrispyCrumbs.videos.json --jsonArray

.\FilesForMongoDB\mongosh.exe "CrispyCrumbs" --eval "db.videos.createIndex({ title: 'text', description: 'text' })"
.\FilesForMongoDB\mongosh.exe "CrispyCrumbs" --eval "db.videos.createIndex({ title: 1 })"
.\FilesForMongoDB\mongosh.exe "CrispyCrumbs" --eval "db.videos.createIndex({ tags: 1 })"

CALL npm install
node server.js
